### ISSUE TITLE
Implement Partner Authentication

### ISSUE THREAD

**Issue by davidlumley** [kaleworsley/omniauth-xero#2]
It'd be great if this OmniAuth strategy implemented the ability to authenticate a [partner application](http://developer.xero.com/documentation/getting-started/partner-applications/) and the relevant certificates.

I'm in a little over my head when it comes to modifying OmniAuth to sign requests with certificates as opposed to HMAC but am happy to contribute if someone could point me in the right direction!

**Comment by toxaq** [comment]
This was a suprisingly small change in the end. You need to overwrite the consumer call to set the HTTP cert attributes

     def consumer
        consumer = ::OAuth::Consumer.new(options.consumer_key, options.consumer_secret, options.client_options)
        consumer.http.open_timeout = options.open_timeout if options.open_timeout
        consumer.http.read_timeout = options.read_timeout if options.read_timeout
        consumer.http.cert = options.client_options[:ssl_client_cert]
        consumer.http.key = options.client_options[:ssl_client_key]
        consumer
      end

and then pass these client_options
    
        :signature_method => 'RSA-SHA1',
        :ssl_client_cert  => OpenSSL::X509::Certificate.new(File.read("#{Rails.root}/config/xero/entrust-cert.pem")),
        :ssl_client_key   => OpenSSL::PKey::RSA.new(File.read("#{Rails.root}/config/xero/entrust-private-nopass.pem")),
        :private_key_file => "#{Rails.root}/config/xero/privatekey.pem",
        :site             => "https://api-partner.network.xero.com",
        :authorize_url    => 'https://api.xero.com/oauth/Authorize',
        :xero_url         => 'https://api-partner.network.xero.com/api.xro/2.0'

Ignore all my junky path references, I was just hacking together a working example strategy (and this works).
